services:
  postgres:
    image: postgres:18
    container_name: substiify-postgres
    restart: unless-stopped
    ports:
      - ${POSTGRES_HOST_PORT:-5440}:5432
    volumes:
      - ${POSTGRES_DATA_PATH:-./postgres-data}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-substiify}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?error}
      - TZ=${POSTGRES_TZ:-Europe/Berlin}

  substiify:
    image: ghcr.io/jackra1n/substiify-v2:release
    container_name: substiify
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${LOGS_PATH:-./logs}:/bot/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
