services:

  postgres:
    image: postgres:16-alpine
    container_name: substiify-postgres
    restart: unless-stopped
    ports:
      - 5440:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=substiify
      - POSTGRES_PASSWORD=example
      - TZ=Europe/Zurich

  substiify:
    image: ghcr.io/jackra1n/substiify-v2:release
    container_name: substiify
    restart: unless-stopped
    volumes:
      - .env:/bot/.env
      - ./logs:/bot/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
