services:

  postgres:
    image: postgres:16-alpine
    container_name: substiify-postgres
    restart: unless-stopped
    ports:
      - 5440:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=substiify
      - POSTGRES_PASSWORD=example
      - TZ=Europe/Zurich

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    ports:
      - 2333:2333
    environment:
      - _JAVA_OPTIONS=-Xmx2G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/

  substiify:
    image: ghcr.io/jackra1n/substiify-v2:release
    container_name: substiify
    restart: unless-stopped
    volumes:
      - .env:/bot/.env
      - ./logs:/bot/logs
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
