name: Create and publish a Docker image

on:
  push:
    branches: ['release']
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      setup-qemu: false
      meta-images: ghcr.io/${{ github.repository }}
      set-meta-labels: true
      sign: 'false'
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
