name: Create and publish a Docker image

on:
  push:
    branches: ['release']
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    permissions:
      contents: read

  basedpyright:
    uses: ./.github/workflows/basedpyright.yaml
    permissions:
      contents: read

  ruff:
    uses: ./.github/workflows/ruff.yaml
    permissions:
      contents: read

  build-and-push-image:
    needs: [tests, basedpyright, ruff]
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      setup-qemu: false
      meta-images: ghcr.io/${{ github.repository }}
      set-meta-labels: true
      sign: 'false'
      build-args: |
        GIT_COMMIT=${{ github.sha }}
        GIT_COMMIT_DATE=${{ github.event.head_commit.timestamp }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
